apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: social-media-analysis
  name: social-media-analysis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: social-media-analysis
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: social-media-analysis
    spec:
      containers:
      - image: beaware/social-media-analysis:IMAGE_TAG
        imagePullPolicy: Always
        name: social-media-analysis
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
        env:
          - name: SECRET_MH_API_KEY
            valueFrom:
             secretKeyRef:
              name: mh-secret2
              key: api_key
          - name: SECRET_MH_BROKERS
            valueFrom:
             secretKeyRef:
              name: mh-secret2
              key: kafka_brokers_sasl
